### ISSUE TITLE
Clarify purpose

### ISSUE THREAD

**Issue by tuxayo** [x13a/Red#3]
Sorry I think don't understand with the brief description.

best guess: It's for when doing a classic call with the dial app, Red will cancel that if the contact is in Signal/Telegram/Threema (how is that known?) and call via there instead.

Is that correct?

**Comment by x13a** [comment]
Yes.

> how is that known?

Signal/Telegram/Threema adds multiple records to contacts to connect via
them (ex: Signal Call <NUMBER>). These records have known mimetypes. Red
checks for it.

**Comment by tuxayo** [comment]
ok, thanks for the clarification :)
Might be worth finding another way to phrase it if other people are confused. Meanwhile we have this issue with the explanation.
